@Clients.Api_HostAddress = http://localhost:5000

POST {{Clients.Api_HostAddress}}/clients/
Accept: application/json
Content-Type: application/json

{
  "name": "Ahmet Tügür",
  "email": "ahmet@random.com",
  "membership": "Regular",
  "BirthDate": "1990-01-01"
}

###
