---
apiVersion: v1
kind: Service
metadata:
  name: clients-api
spec:
  type: NodePort
  selector:
    app: clients-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  - name: tcp
    port: 8081
    targetPort: 8080
    nodePort: 30002