---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-broker
  labels:
    app: rabbitmq-broker
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-broker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq-broker
    spec:
      containers:
      - name: rabbitmq-broker
        image: docker.io/library/rabbitmq:3.13-management
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 5672
        - name: management
          containerPort: 15672
        envFrom:
        - configMapRef:
            name: rabbitmq-broker-env
      terminationGracePeriodSeconds: 180